config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  
  resources :users do
    resources :lists
  end

  resources :properties do
    resources :images
  end
  resources :sessions, only: [:new, :create]
  delete '/logout' => 'sessions#destroy', as: :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :property
  has_attached_file :picture,
    styles: {medium: "300x300>", thumb: "100x100>"},
    default_url: "/images/:style/missing.png"
  
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :user
    has_many :images
    has_attached_file :image_file,
     styles: {large: "1080x640#", medium: "600x300#", thumb: "100x100#"},
     default_url: "/images/:style/missing.png"

    validates_attachment_content_type :image_file, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :properties
    validates :email, :name, presence: true
    validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authorize

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authorize
    unless logged_in?
      flash[:danger] = "Access Denied."
      redirect_to new_session_path
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def index
    @images = Image.all
    @property = Property.find(params[:property_id])
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
    @property = Property.find(params[:property_id])
    unless current_user.id == @property.user.id
      redirect_to property_path(@property), flash: {danger: "Access Denied"}
    end
  end

  def create
    @property = Property.find(params[:property_id])
    unless current_user.id == @property.user.id
      redirect_to properties_path, flash: {danger: "Access Denied"}
    end
    @image = @property.images.new(image_params)
    if @image.save
      redirect_to property_path(@property)
    else
      redirect_to new_image_path
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @image = Image.find(params[:id])
    if @image.destroy
      redirect_to property_images_path
    end
  end

  private
  def image_params
    params.require(:image).permit(:caption, :picture)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  before_action :authorize, except: [:index, :show]

  def index
    @properties = Property.all
  end

  def new
    @property = Property.new
  end

  def show
    @property = Property.find(params[:id])
  end

  def create
    @property = current_user.properties.new(property_params)
    if @property.save
      redirect_to user_path(@current_user)
    else
      redirect_to new_property_path
    end
  end

  def edit
    @property = Property.find(params[:id])
    unless current_user.id == @property.user.id
      redirect_to properties_path, flash: {danger: "Access Denied"}
    end
  end

  def update
    @property = Property.find(params[:id])
    if @property.update(property_params)
      redirect_to property_path(@property)
    else
      redirect_to edit_property_path(@property)
    end
  end

  def destroy
    @property = Property.find(params[:id])
    @property.images.each do |i|
      i.destroy
    end
    if @property.destroy
      redirect_to user_path(@current_user)
    end
  end

  private

  def property_params
    params.require(:property).permit(:price, :address, :sq_footage, :no_of_bedroom, :no_of_bathroom, :description, :image, :image_file)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:danger] = "Incorrect email or password"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show, :edit, :update, :destroy]
  
  def index
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:danger] = "Please provide all required fields."
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(@current_user), flash: {danger: "Access Denied"}
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    if @current_user.destroy
      session[:user_id] = nil
      redirect_to new_user_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :phone, :address, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<p>Find me in app/views/images/edit.html.erb</p>

app/views/images/index.html.erb
<div class="container-fluid text-center">
  <div class="row">
    <div class="col-2"></div>
      <div class="col-8">
          <h3 class="bg-secondary border border-danger rounded">More photos for <%= @property.address %> </h3>
          <% @property.images.each do |i| %>
          <div class="border border-danger">
              <p style="font-size: 2rem;"><%= link_to i.caption, property_image_path(i.property.id, i.id) %></p>
              <%= image_tag i.picture.url, :style => "max-width: 100%;" %>
          </div>
          <hr class="border border-danger">
          <% end %>
        <div>
            <p class="btn btn-outline-danger btn-lg"><%= link_to 'Go Back', property_path(@property) %></p>
        </div>
      </div>
    <div class="col-2"></div>
  </div>
</div>

app/views/images/new.html.erb
<h1>Add more pictures of your property</h1>

<%= form_for [@property, @image] do |f| %>
<div class="form-group">
    <%= f.label :caption, 'Caption: ' %>
    <%= f.text_field :caption, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :picture, 'Add picture: ' %>
    <%= f.file_field :picture, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.submit 'Add', class: 'btn btn-success' %>
</div>
<% end %>

app/views/images/show.html.erb
<h3>Listing for: <%= link_to @image.property.address, property_path(@image.property.id)%></h3>
<h4><%= @image.caption %></h4>
<% unless current_user.id != @image.property.user.id %>
<p><%= link_to 'Delete', property_image_path(@image.property), data: {confirm: "Are you sure?"}, method: :delete, class: 'btn btn-danger' %></p>
<% end %>
<%= image_tag @image.picture.url, :style => "max-width: 100%;" %>

app/views/images/update.html.erb
<h1>Images#update</h1>
<p>Find me in app/views/images/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocalHomes4SaleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/partials/navbar' %>
    <%= render 'layouts/partials/flash' %>
    <div class="container-fluid" style="margin: 15px auto;">
        <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/partials/_flash.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>">
    <%= value %>
</div>
<% end %>

app/views/layouts/partials/_footer.html.erb
<nav class="navbar fixed-bottom navbar-danger bg-danger">
        <a class="navbar-brand">&#169 LocalHomes4Sale Inc. - Created by Mihir Naik.</a>
</nav>

app/views/layouts/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-danger">
    <a class="navbar-brand" href="<%= properties_path%>">🏡🏠🏘🏛 LocalHomes4Sale 🏛🏘🏠🏡</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <% if logged_in? %>
                <li class="nav-item"> 
                    <%= link_to "Hi #{current_user.name}!", user_path(current_user), class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Log Out', logout_path, method: 'delete', class:"nav-link" %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to 'Sign Up', new_user_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Log In', new_session_path, class:"nav-link" %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/properties/create.html.erb
<h1>Properties#create</h1>
<p>Find me in app/views/properties/create.html.erb</p>

app/views/properties/destroy.html.erb
<h1>Properties#destroy</h1>
<p>Find me in app/views/properties/destroy.html.erb</p>

app/views/properties/edit.html.erb
<h1>Properties#edit</h1>

<%= form_for @property do |f| %>
<div class="form-group">
        <%= f.label :price, 'Sale Price($): '%>
        <%= f.text_field :price, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :address, 'Address: '%>
        <%= f.text_field :address, class: 'form-control'  %>
    </div>
    <div class="form-group">
        <%= f.label :sq_footage, 'Square Footage: '%>
        <%= f.text_field :sq_footage, class: 'form-control'  %>
    </div>
    <div class="form-group">
        <%= f.label :no_of_bedroom, 'No. of Bedroom: '%>
        <%= f.number_field :no_of_bedroom, class: 'form-control'  %>
    </div>
    <div class="form-group">
        <%= f.label :no_of_bathroom, 'No. of Bathroom: '%>
        <%= f.number_field :no_of_bathroom, class: 'form-control'  %>
    </div>
    <div class="form-group">
        <%= f.label :description, 'Description: '%>
        <%= f.text_area :description, class: 'form-control'  %>
    </div>
    <div class="form-group">
        <%= f.label :image_file, 'Cover photo: '%>
        <%= f.file_field :image_file, class: 'form-control'  %>
    </div>
<div class="form-group">
    <%= f.submit 'Save Changes', class: 'btn btn-success' %>
</div>
<% end %>

<div class="form-group">
        <%= link_to 'Delete Property', property_path, data: {confirm: "Are you sure?"}, method: :delete, class: 'btn btn-danger' %>
</div>

app/views/properties/index.html.erb
<hr class="border border-danger">
<div class="container-fluid">
    <div class="row justify-content-center text-center">
        <% @properties.each do |p| %>
            <div class="col-sm-4">
                <div class="card bg-light mb-3 border border-danger rounded" style="max-width: 30rem;">
                    <div class="list-group list-group-flush">
                        <img src="<%= p.image_file %>" alt="" class="card-img-top" style="max-height: 300px;" >
                        <div class="card-body"> 
                            <h4 class="card-title">Address: <%= p.address %></h4>
                            <p class="card-text">Price($): <%= p.price %></p>
                            <p class="card-link"><%= link_to 'More details here', property_path(p.id) %></p>
                        </div>
                        <div class="card-body">
                            <p class="card-link">Listing provided by: <%= link_to p.user.name, user_path(p.user) %> about <%= time_ago_in_words p.created_at %></p>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
<hr class="border border-danger">

app/views/properties/new.html.erb
<h1>Let's sell your property!!!</h1>
<h3 class="text-muted">Fill out the following:</h3>

<%= form_for @property do |f| %>
<div class="form-group">
    <%= f.label :price, 'Sale Price($): '%>
    <%= f.text_field :price, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :address, 'Address: '%>
    <%= f.text_field :address, class: 'form-control'  %>
</div>
<div class="form-group">
    <%= f.label :sq_footage, 'Square Footage: '%>
    <%= f.text_field :sq_footage, class: 'form-control'  %>
</div>
<div class="form-group">
    <%= f.label :no_of_bedroom, 'No. of Bedroom: '%>
    <%= f.number_field :no_of_bedroom, class: 'form-control'  %>
</div>
<div class="form-group">
    <%= f.label :no_of_bathroom, 'No. of Bathroom: '%>
    <%= f.number_field :no_of_bathroom, class: 'form-control'  %>
</div>
<div class="form-group">
    <%= f.label :description, 'Description: '%>
    <%= f.text_area :description, class: 'form-control'  %>
</div>
<div class="form-group">
    <%= f.label :image_file, 'Cover photo: '%>
    <%= f.file_field :image_file, class: 'form-control'  %>
</div>
<div class="form-group">
    <%= f.submit 'Post', class: 'btn btn-success' %>
</div>
<% end %>

app/views/properties/show.html.erb
<div class="container-fluid text-center">
    <div class="row">
        <div class="col-4">
            <h5 class="font-weight-bold">Address: <%= @property.address %></h5>
            <h5 class="font-weight-bold">Price($): <%= @property.price %></h5>
            <p>Square Footage: <%= @property.sq_footage%></p>
            <p>No. of Bedroom: <%= @property.no_of_bedroom %></p>
            <p>No. of Bathroom: <%= @property.no_of_bathroom %></p>
            <p>Description: <%= @property.description %></p>
            <h5>Contact: <u><%= @property.user.name %></u> @ <%= @property.user.phone %> or <%= mail_to @property.user.email, nil %></h5>
            <% if current_user %>
            <% unless current_user.id != @property.user.id %>
            <p class="btn btn-outline-danger btn-lg"><%= link_to 'Add more photos', new_property_image_path(@property) %></p>
            <p class="btn btn-outline-danger btn-lg"><%= link_to 'Edit', edit_property_path(@property) %></p>
            <% end %>
            <% end %>
            
            <p class="btn btn-outline-danger btn-lg"><%= link_to 'View more photos', property_images_path(@property) %></p>
            <p class="btn btn-outline-danger btn-lg"><%= link_to 'Go Back', properties_path %></p>    
        </div>
        <div class="col-8">
            <div>
                <img src="<%= @property.image_file %>" alt="" class="border border-danger rounded" style="max-width: 100%;" >
            </div>
        </div>
      </div>
</div>

app/views/properties/update.html.erb
<h1>Properties#update</h1>
<p>Find me in app/views/properties/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit your account</h1>

<%= form_for @user do |f| %>
<div class="form-group">
                <%= f.label :name, 'Full Name*', class: '' %>
                <%= f.text_field :name, class: 'form-control', placeholder: "`John Doe`" %>
        </div>
        <div class="form-group">
                <%= f.label :phone, 'Phone', class: ''%>
                <%= f.text_field :phone, class: "form-control", placeholder: "`1234567890`" %>
        </div>
        <div class="form-group">
                <%= f.label :address, 'Address', class: ''%>
                <%= f.text_field :address, class: "form-control", placeholder: "`Street Address, City, State, ZipCode`" %>
        </div>
        <div class="form-group">
                <%= f.label :email, 'Email*', class: ''%>
                <%= f.text_field :email, class: "form-control", placeholder: "`email@domain.com`" %>
        </div>
        <div class="form-group">
                <%= f.label :password, 'Password*', class: ''%>
                <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group">
                <%= f.label :password_confirmation, 'Confirm Password*', class: ''%>
                <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
    <div class="form-group">
        <%= f.submit 'Save changes', class: "btn btn-success"%>
    </div>
<% end %> 

<div class="form-group">
        <%= link_to 'Delete Account', new_user_path, data: {confirm: "Are you sure?"}, method: :delete, class: "btn btn-danger" %>
</div>

app/views/users/index.html.erb
<div class="container-fluid">
    <div class="row" style="margin-top: 100px;">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="jumbotron">
                <h1 class="display-3">Welcome to Local Homes 4 Sale</h1>
                <p class="lead">Whether you are in the market for selling or buying a property, you have come to the right palce.</p>
                <hr class="my-4">
                <p>Go ahead and sign up to access all the features this app offers. Once you are logged in, you can add your own listing, checkout other active listings and also contact the listing provider directly to take the next step.</p>
                <p class="lead">
                    <a class="btn btn-danger btn-lg" href="<%= properties_path %>" role="button">Check out listings</a>
                    <a class="btn btn-danger btn-lg" href="<%= new_user_path %>" role="button">Sign up</a>
                    <a class="btn btn-danger btn-lg" href="<%= new_session_path %>" role="button">Log in</a>
                </p>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
<%= render 'layouts/partials/footer' %>
</div>

app/views/users/new.html.erb
<div class="container-fluid text-center">
    <h1 style="margin: 50px;">Create new account: </h1>
        <div class="row">
                <div class="col-2"></div>
                <div class="col-8">
                    <%= form_for @user do |f| %>
                        <div class="form-group">
                                <%= f.label :name, 'Full Name*', class: '' %>
                                <%= f.text_field :name, class: 'form-control text-center', placeholder: "Your Full Name" %>
                        </div>
                        <div class="form-group">
                                <%= f.label :phone, 'Phone', class: ''%>
                                <%= f.text_field :phone, class: 'form-control text-center', placeholder: "Your Phone number" %>
                        </div>
                        <div class="form-group">
                                <%= f.label :address, 'Address', class: ''%>
                                <%= f.text_field :address, class: 'form-control text-center', placeholder: "Your Street Address, City, State, ZipCode" %>
                        </div>
                        <div class="form-group">
                                <%= f.label :email, 'Email*', class: ''%>
                                <%= f.text_field :email, class: 'form-control text-center', placeholder: "your-email@example.com" %>
                        </div>
                        <div class="form-group">
                                <%= f.label :password, 'Password*', class: ''%>
                                <%= f.password_field :password, class: 'form-control text-center',placeholder: "Choose something secure" %>
                        </div>
                        <div class="form-group">
                                <%= f.label :password_confirmation, 'Confirm Password*', class: ''%>
                                <%= f.password_field :password_confirmation, class: 'form-control text-center',placeholder: "Confirm your password" %>
                        </div>
                        <div>
                                <%= f.submit 'Sign Up', class: "btn btn-success btn-lg"%>
                        </div>
                    <% end %> 
                </div>
                <div class="col-2"></div>
        </div>
<%= render 'layouts/partials/footer' %>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-2">
            <div class="text-center rounded" id="welcomeDashboard">
                <p class=" btn-outline-danger btn-sm  border-danger"><%= link_to 'Checkout Active Listings', properties_path %></p>
                <p class=" btn-outline-danger btn-sm  border-danger"><%= link_to 'Add new listing', new_property_path %></p>
                <p class=" btn-outline-danger btn-sm  border-danger"> <%= link_to 'Edit your Account', edit_user_path(@user) %></p>
            </div>
        </div>
        <div class="col-10">
            <% unless current_user.id == @user.id %>
                <h3 class='card-text text-center'><%= @user.name %>'s listings</h3>
            <% end %>
            <div class="card-deck">
                <% @user.properties.each do |p| %>
                    <div class="col-6">
                        <div class="card bg-light mb-3 border border-danger rounded">
                            <%= image_tag p.image_file.url(:medium), class: "card-img-top img-thumbnail" %>
                            <div class="card-body text-center">
                                <h4 class="card-title"><%= p.address %></h4>
                                <p lass="card-text"> $ <%= p.price %></p>
                                <p class="card-link"><%= link_to 'More details here', property_path(p.id) %></p>
                                <% if current_user.id == @user.id %>
                                    <p class="btn btn-outline-danger"><%= link_to 'Edit property', edit_property_path(p) %></p>
                                    <p class="btn btn-outline-danger"><%= link_to 'Add more photos', new_property_image_path(p) %></p>
                                <% end %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>